// auto generated by go tool dist

package cfg

const DefaultCC = `aarch64-linux-android-clang`
const DefaultCXX = `aarch64-linux-android-clang++`
const DefaultPkgConfig = `/home/builder/.termux-build/_lib/15.2-aarch64-21-v12/bin/aarch64-linux-android-pkg-config`
