// auto generated by go tool dist

package objabi

import "runtime"

const defaultGOROOT = `/data/data/com.termux/files/usr/lib/go`
const defaultGO386 = `sse2`
const defaultGOARM = `5`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `go1.9`
const stackGuardMultiplier = 1
const goexperiment = ``
