// auto generated by go tool dist

package main

const defaultCC = `aarch64-linux-android-clang`
const defaultCXX = `aarch64-linux-android-clang++`
const defaultPkgConfig = `/home/builder/.termux-build/_lib/15.2-aarch64-21-v12/bin/aarch64-linux-android-pkg-config`
