###############################################################
##
##  Profile for zsh
##
###############################################################

##
## Set the strict file mode creation mask so
## only user with Termux UID can access them.
##
umask 077
